#!/bin/bash
cd ../data && \
../../../bin/gconvert tileset.xml && \
../../../bin/midiconv -f 8 -1 -2 -3 midisong.mid midisong.h && \
#../../../bin/midiconv -f 8 -1 -2 -3 osirisfinal.mid osirisfinal.h && \
cd ../default && \
make clean && \
make